name: fluxdo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.15+2026020600

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  http: ^1.6.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  native_dio_adapter: ^1.3.0
  flutter_secure_storage: ^9.2.2
  flutter_inappwebview: ^6.1.5
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_riverpod: ^3.1.0
  flutter_widget_from_html: ^0.17.1
  extended_image_lite:
    path: packages/extended_image_lite
  re_highlight: ^0.0.3
  google_fonts: ^8.0.0
  share_plus: ^12.0.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.12.0
  # NOTE: If updating font_awesome_flutter, run:
  #   dart run tool/gen_fa_name_mapping.dart
  shared_preferences: ^2.5.4
  dynamic_color: ^1.8.1
  scroll_to_index: ^3.0.1
  visibility_detector: ^0.4.0+2
  markdown: ^7.2.2
  image_picker: ^1.2.1
  gal: ^2.3.2
  pangutext:
    path: packages/pangutext
  flutter_local_notifications: ^19.5.0
  flutter_svg: ^2.2.3
  html: ^0.15.5
  dio_smart_retry: ^7.0.1
  extended_nested_scroll_view: ^6.0.0
  popover: ^0.4.0
  uuid: ^4.5.2
  logger: ^2.5.0
  path_provider: ^2.1.5
  path: ^1.9.1
  dns_client: ^1.3.1
  cronet_http: ^1.7.0
  package_info_plus: ^8.1.2
  pro_image_editor: ^11.18.4
  flutter_image_compress: ^2.4.0
  flutter_math_fork: ^0.7.2
  device_info_plus: ^12.3.0
  ota_update: ^7.1.0
  app_links: ^7.0.0

  ffi: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/images/
    - assets/certs/













